# Generated by Django 4.2.5 on 2023-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_category_tag_topic_category_topic_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='topics/%Y/%m/%d/'),
        ),
    ]
